service: herculis

provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameters"
        - "ssm:PutParameter"
      Resource: "arn:aws:ssm:*:*:*"
  environment:
    pvo_key: XXXXXXXX
    pvo_systemid: XXXXXXXX
    sgDeviceId: XXXXXXXX
    sgPlantId: XXXXXXXX
    sgUserId: XXXXXXXX

functions:
  liveUpdate:
    handler: herculis.lambda_handler
    events:
      - schedule:
          rate: cron(0/5 * * * ? *)
          enabled: true
