service: herculis

provider:
  name: aws
  stage: production
  runtime: python2.7
  region: us-west-2
  memorySize: 128
  timeout: 300
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameters"
        - "ssm:PutParameter"
      Resource: "arn:aws:ssm:*:*:*"
  environment:
    pvo_key: XXXXXXXX
    pvo_systemid: XXXXXXXX
    sgDeviceId: XXXXXXXX
    sgPlantId: XXXXXXXX
    sgUserId: XXXXXXXX

package:
  include:
    - herculis.py
  exclude:
    - .git/**
    - docs/**
    - README.md
functions:
  liveUpdate:
    handler: herculis.lambda_handler
    events:
      - schedule:
          rate: cron(0/5 * * * ? *)
          enabled: true
