service: herculis

provider:
  name: aws
  stage: production
  runtime: python2.7
  region: us-west-2
  memorySize: 128
  timeout: 300
  environment:
    # PVOutput API settings, see https://pvoutput.org/account.jsp
    pvo_key: XXXXXXXX
    pvo_systemid: XXXXXXXX
    # Sungrow settings
    sgDeviceId: XXXXXXXX

package:
  include:
    - herculis.py
  exclude:
    - .git/**
    - docs/**
    - README.md
functions:
  herculis:
    name: herculis
    description: Fetch latest Solar metrics and send to PV Output
    handler: herculis.lambda_handler
    events:
      - schedule:
          name: run-lambda-herculis-every-five-mins
          rate: cron(0/5 * * * ? *)
          description: Used by the Herculis Lamdba function.
          enabled: true
